# Generated by Django 4.1.7 on 2023-03-06 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="user_id",
        ),
    ]
